# Use an official Node runtime as a parent image
FROM node:16

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port the app runs on
EXPOSE 80

# Command to run the application
CMD ["npm", "start"]

# # Use an official Node.js runtime as a parent image
# FROM node:14-alpine

# # Set the working directory
# WORKDIR /app

# # Copy package.json and package-lock.json
# COPY package*.json ./

# # Install dependencies
# RUN npm install

# # Copy the rest of the application code
# COPY . .

# # Build the React application
# RUN npm run build

# # Use an official Nginx image to serve the built app
# FROM nginx:alpine

# # Copy the built files to the Nginx HTML directory
# COPY --from=0 /app/build /usr/share/nginx/html

# # Expose the port that the container will run on
# EXPOSE 80

# # Start Nginx server
# CMD ["nginx", "-g", "daemon off;"]
