version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"  # Use port 5001 on the host and port 5000 in the container
    environment:
      - NODE_ENV=production
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: